"""add ats fields to jobs

Revision ID: a77d9774fc86
Revises: 89aea4df0970
Create Date: 2026-03-01 04:07:56.494948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a77d9774fc86'
down_revision: Union[str, Sequence[str], None] = '89aea4df0970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ats_score', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('ats_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('ats_matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('ats_missing_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ats_missing_keywords')
    op.drop_column('jobs', 'ats_matched_keywords')
    op.drop_column('jobs', 'ats_breakdown')
    op.drop_column('jobs', 'ats_score')
    # ### end Alembic commands ###
